project_id = "pgavnutkwiiovdvbrbcl"

[functions.auth-rate-limiter]
verify_jwt = false

[functions.elevenlabs-sfx]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.elevenlabs-scribe-token]
verify_jwt = false

[functions.youtube-viewer-count]
verify_jwt = false

[functions.gyani-chat]
verify_jwt = false

[functions.krishna-ai]
verify_jwt = false

[functions.check-live-status]
verify_jwt = false